### ISSUE TITLE
Add Yii and Slim frameworks

### ISSUE THREAD

**Issue by sizeg** [odan/learn-php#4]
Hi,

I suggest to add Yii framework cause it's as popular as has its own way of growth. It's really very fast framework.

Also I suggest Slim as it's similar to Symfony and Laravel but it slim and interesting to build as a small projects as a huge one.

**Comment by odan** [comment]
Hi @sizeg 

Thank you for your request, but I'm trying to keep this list as short as possible, even if there are still a lot of good things out there (like Yii).
  
The Slim framework is already listed under the section [Micro Frameworks](https://odan.github.io/learn-php/#micro-frameworks).
